### ISSUE TITLE
Code duplication / regression format

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#59]
I'm curious why there's a `ourSubjects_function_prediction()` and `noCMTF_function_prediction()`. Is it because the former only uses the Alter subjects? In this case I'd suggest calling `noCMTF_function_prediction()`, then filtering down to the Alter subjects before calculating the accuracy. It makes sense to only look at those subjects when calculating the accuracy. However, we should be able to use the extra subjects when factoring and building the model, since our method makes it possible to use them.

**Comment by murphymadeleine21** [comment]
ourSubjects_function_prediction() is essentially just a helper function for figure 10 since we wanted to specifically subset subjects left out of Alter and you can't do that after calling noCMTF_function_predictions because it seems to drop some subjects and change the order.

**Comment by aarmey** [comment]
Meaning noCMTF_function_predictions ends up missing subjects that are in Alter? How is that?

**Comment by murphymadeleine21** [comment]
No, noCMTF_function_predictions currently does 174/181 of the patients I believe (only missing ones that have Nans in their data). So it's getting all of Alter's subjects + more. However, because we drop some in the process, the ordering gets changed and I can't just access the data to look at the subjects that were indeed left out of Alter, because their index has changed.
The helper function essentially subsets the subjects that Alter specifically did not capture _before_ running a regression to get predictions, so that we know this is only the subjects that Alter could not capture
